### ISSUE TITLE
Error when pipeline infers resource schema automatically

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/pm#99] opened 2018-01-24 08:32 UTC
## Acceptance criteria
* [ ] when the pipeline infers source schema automatically, it will pass the validation.

## Analysis
We implemened [allow infer schema for resources](https://github.com/datahq/datahub-client/issues/10) feature, which is very cool and reduces manual work when automating a dataset.

But when the pipeline infers resource schema automatically, this schema does not pass the validator.

#### Examples

Auto source schema infer in the 'GDP' dataset:
https://github.com/datasets/gdp/blob/2e41b0b79005f51269826eb7f29df8636dbbbc9f/.datahub/flow.yaml#L7
```yaml
inputs:
  -
    kind: datapackage
    parameters:
      resource-mapping:
        gdp: http://api.worldbank.org/indicator/NY.GDP.MKTP.CD?format=csv
```
The source csv header has a redundant comma.
```csv
"2015","2016","2017",
```

Result:
https://testing.datahub.io/AcckiyGerman/gdp
![image](https://user-images.githubusercontent.com/11707682/35322119-c6d4a042-00f1-11e8-92cf-1ad1e796f2e2.png)

**Comment by zelima** [comment] 2018-01-24 08:35
This is not a bug related to us, but the resource data is just invalid according to the schema (it should not have a blank header).

Question to answer here would be:
* should we validate source data at all?

**Comment by AcckiyGerman** [comment] 2018-01-24 08:40
Yes, the source csv header 
```csv
"2015","2016","2017",
```
has redundant comma

**Comment by zelima** [comment] 2018-03-08 13:19
WONTFIX this is not related to us

**Closed by zelima** 2018-03-08 13:19 UTC
Labels: question
